name             'miner'
maintainer       'Giovanni Toraldo'
maintainer_email 'me@gionn.net'
license          'Apache2'
description      'Installs/Configures mining software for crypto'
long_description 'Installs/Configures mining software for crypto'
version          '0.0.1'
depends          'ark', '~> 0.8.0'
depends          'apt', '~> 2.3.8'
